### ISSUE TITLE
Addon no longer auto-accepts/completes quests (v110000.75-Release)

### ISSUE THREAD

**Issue by Klunkk** [p3lim-wow/QuickQuest#102]
**Describe the bug**
Version 110000.75-Release does not auto-accept/complete quests.

**How to reproduce**
It was reproducible for me upon interacting with any NPC for any quest stage.
Attempted to clear saved variables, uninstall, and reinstall the current version, but that had no effect.
Reverting to v110000.73-Release fixed the issue.

**What did you expect?**
Expected result was the normal auto-accept/complete for each quest.

**Screenshots**
No error messages were produced.
No screenshots possible since the auto-accept/complete action appears to be broken.

**Comment by p3lim** [comment]
A change in .75, if you read the changelog, was that warband-completed quests will not be picked up by default (just like low-level quests) unless the player tracks them (e.g. through minimap tracking or through the world map).

**Comment by Klunkk** [comment]
I appreciate the clarification. Is there still a way to enable this via the
options that I may have missed?

I suppose I'm not 100% clear on the functionality.  If I track low level
quests, for example, will the addon then auto-complete or has that been
completely removed?

Thanks again.

**Comment by p3lim** [comment]
From the minimap or the world map you have tracking menues with these two options:
![image](https://github.com/user-attachments/assets/1eb396b8-0f44-4c40-984f-15dd9e114a90)
If you enable "Low-Level Quests" then QuickQuest will accept quest that are consider low level for your character (e.g. no xp).
If you enable "Warband Completed Quests" then QuickQuest will accept quests that have already been completed on your account.

Since the tracking state of these are per-character while QuickQuest's options are not, this seemed like the best way to deal with this.
