### ISSUE TITLE
Alterac soldiers blood.

### ISSUE THREAD

**Issue by hasnogaems** [p3lim-wow/QuickQuest#38]
When have alot of blood in inventory it still turn in quests for 1 blood inbstead of 5 blood. Take very very long.

**Comment by p3lim** [comment]
I need some things to fix this, since I don't play classic:
- The exact item ID (link to wowhead will do)
- The exact quest IDs (links to wowhead will do)
- The event that triggers when you talk to the quest giver
    Run this macro before talking and see what pops up:
```lua
/run local f=CreateFrame'Frame';f:RegisterEvent'QUEST_GREETING';f:RegisterEvent'GOSSIP_SHOW';f:SetScript('OnEvent',print)
```

This should either print `GOSSIP_SHOW` or `QUEST_GREETING`, let me know which one it is.
